"""create database

Revision ID: 419b5032ef0
Revises: None
Create Date: 2013-11-24 22:42:53.434275

"""

# revision identifiers, used by Alembic.
revision = '419b5032ef0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from datetime import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'feed',
        sa.Column('feed_id', sa.Integer(), sa.Sequence('feed_id_seq'), primary_key=True),
        sa.Column('feed_title', sa.String(255), nullable=False),
        sa.Column('feed_url', sa.String(255), nullable=False),
        sa.Column('feed_link', sa.Text(), nullable=False),
        sa.Column('last_update_time', sa.DateTime(), nullable=False),
        sa.Column('create_time', sa.DateTime, nullable=False, default=datetime.now())
    )
    op.create_table(
        'feed_item',
        sa.Column('item_id', sa.Integer(), sa.Sequence('feed_item_id_seq'), primary_key=True),
        sa.Column('feed_id', sa.Integer()),
        sa.Column('item_title', sa.String(250), nullable=False),
        sa.Column('item_descrition', sa.Text()),
        sa.Column('item_url', sa.Text(), nullable=False),
        sa.Column('content', sa.Text()),
        sa.Column('star', sa.Boolean(), default=False),
        sa.Column('save', sa.Boolean(), default=False),
    )
    op.create_table(
        'tag',
        sa.Column('tag_id', sa.Integer(), sa.Sequence('tag_id_seq'), primary_key=True),
        sa.Column('tag_name', sa.String(50), sa.Sequence('tag_name'), nullable=True),
        sa.Column('count', sa.Integer(), default=0)
    )
    op.create_index('ix_feed_feed_id', 'feed', ['feed_id'])
    op.create_index('ix_feed_feed_title', 'feed', ['feed_title'])
    op.create_index('ix_feed_feed_url', 'feed', ['feed_url'])
    op.create_index('ix_feed_feed_last_update_time', 'feed', ['last_update_time'])
    op.create_index('ix_feed_feed_create_time', 'feed', ['create_time'])
    op.create_index('ix_feed_feed_item_item_id', 'feed_item', ['item_id'])
    op.create_index('ix_feed_feed_item_feed_id', 'feed_item', ['feed_id'])
    op.create_index('ix_feed_feed_item_item_title', 'feed_item', ['item_title'])
    op.create_index('ix_feed_feed_item_star', 'feed_item', ['star'])
    op.create_index('ix_feed_feed_item_save', 'feed_item', ['save'])
    op.create_index('ix_tag_tag_id', 'tag', ['tag_Id'])
    op.create_index('ix_tag_tag_name', 'tag', ['tag_name'])
    op.create_index('ix_tag_count', 'tag', ['count'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    op.drop_table('feed_item')
    op.drop_table('tag')

    op.drop_index('ix_feed_feed_id')
    op.drop_index('ix_feed_feed_title')
    op.drop_index('ix_feed_feed_url')
    op.drop_index('ix_feed_feed_last_update_time')
    op.drop_index('ix_feed_feed_create_time')
    op.drop_index('ix_feed_feed_item_item_id')
    op.drop_index('ix_feed_feed_item_feed_id')
    op.drop_index('ix_feed_feed_item_item_title')
    op.drop_index('ix_feed_feed_item_star')
    op.drop_index('ix_feed_feed_item_save')
    op.drop_index('ix_tag_tag_id')
    op.drop_index('ix_tag_tag_name')
    op.drop_index('ix_tag_count')
    ### end Alembic commands ###
